### ISSUE TITLE
Write the assigned parts of the Milestone 3 Report

### ISSUE THREAD

**Issue by zbuseaydin** [bounswe/bounswe2024group4#630]
### Issue Type

Deliverable

### Issue Description

- [ ] create the table for the work of each member in Progress Based on Teamwork
- [ ] summary of my work in Progress Based on Teamwork
- [ ] Status of Requirements - frontend
- [ ] User Interface / User Experience - frontend
- [ ] Provide a scenario encompassing all core functionalities of your project. Describe in detail the features and work completed to realize this scenario

**Comment by zbuseaydin** [comment]
the table is created https://github.com/bounswe/bounswe2024group4/wiki/Milestone-3-Report#summary-of-work-performed-by-each-team-member

**Comment by zbuseaydin** [comment]
wrote 2 scenarios: [one for super members](https://github.com/bounswe/bounswe2024group4/wiki/Milestone-3-Report#scenario-1-super-user-kaan), [one for normal members](https://github.com/bounswe/bounswe2024group4/wiki/Milestone-3-Report#scenario-2-newbie-batuhan)
added the [features and work completed for the scenarios](https://github.com/bounswe/bounswe2024group4/wiki/Milestone-3-Report#features-and-work-completed-for-the-scenarios)

**Comment by zbuseaydin** [comment]
updated [Status of Requirements - frontend](https://github.com/bounswe/bounswe2024group4/wiki/Milestone-3-Report#status-of-requirements)

**Comment by zbuseaydin** [comment]
added [ui/ux frontend](https://github.com/bounswe/bounswe2024group4/wiki/Milestone-3-Report#frontend)

**Comment by zbuseaydin** [comment]
wrote my part in [individual contributions](https://github.com/bounswe/bounswe2024group4/wiki/Milestone-3-Report#individual-contributions)
