### ISSUE TITLE
Prepare "Progress Based on Teamwork" Section for Milestone Report

### ISSUE THREAD

**Issue by nucan25** [bounswe/bounswe2024group4#632]
### Issue Type

Deliverable

### Issue Description

- [x] My Work Summary (Progress Based on Teamwork)
- [x] Requirements Status (Mobile)
- [x] UI/UX (Mobile)
- [x] W3C Standards Compliance
- [x] Individual Contributions

**Comment by nucan25** [comment]
I completed all sections listed above except for **W3C Standards Compliance**, which was prepared by [Murat Can Kocakulak](https://github.com/bounswe/bounswe2024group4/wiki/Murat-Can-Kocakulak) due to his expertise on the topic.
